var vbjq=jQuery;
(function(d){var b=function(){};b.test=document.createElement("div");b.isEmpty=function(b){return 0==b.replace(/^\s+|\s+$/g,"").length};b.isNumber=function(b){return!isNaN(parseFloat(b))&&isFinite(b)};b.isMobile=function(){return/Android|webOS|iPhone|iPad|iPod|sony|BlackBerry/i.test(navigator.userAgent)};b.isChrome=function(){return!!d.chrome&&!!d.chrome.webstore};b.isSafari=function(){return 0<Object.prototype.toString.call(d.HTMLElement).indexOf("Constructor")};b.hasLocalStorage=function(){try{return"localStorage"in
d&&null!==d.localStorage}catch(P){return!1}};b.isAndroid=function(){return-1<navigator.userAgent.indexOf("Android")};b.volumeCanBeSet=function(){var b=document.createElement("audio");if(!b)return!1;b.volume=0;return 0==b.volume?!0:!1};b.hasFullscreen=function(){return b.test.requestFullscreen||b.test.mozRequestFullScreen||b.test.msRequestFullscreen||b.test.oRequestFullscreen||b.test.webkitRequestFullScreen};b.qualifyURL=function(b){var d=document.createElement("a");d.href=b;return d.href};b.supportsWebGL=
function(){try{return!!d.WebGLRenderingContext&&!!document.createElement("canvas").getContext("experimental-webgl")}catch(P){return!1}};d.VBUtils=b})(window);
(function(d,b){d.VBPlaylistManager=function(d){function S(){var b=k,f=[],d=[],p;for(p=0;p<b;p++)f[p]=p;for(p=0;p<b;p++){var q=Math.round(Math.random()*(f.length-1));d[p]=f[q];f.splice(q,1)}D=d}var y=this,T=d.loopingOn,p=d.randomPlay,k,q=!1,f=-1,ea,sa,fa=!1,D=[],P=!1;this.setCounter=function(d,ea){"undefined"===typeof ea&&(ea=!0);f=ea?f+parseInt(d,10):parseInt(d,10);if(isNaN(f))alert("VBPlaylistManager message: No active media, counter = "+f);else if(q=!1,T){if(p)if(f>k-1){f=D[k-1];S();if(D[0]==f){var ra=
D.splice(0,1);D.push(ra)}f=0;b(y).trigger("VBPlaylistManager.PLAYLIST_END_ALERT")}else 0>f&&(f=D[0],S(),D[k-1]==f&&(ra=D.splice(k-1,1),D.unshift(ra)),f=k-1);else f>k-1?(f=0,b(y).trigger("VBPlaylistManager.PLAYLIST_END_ALERT")):0>f&&(f=k-1);b(y).trigger("VBPlaylistManager.COUNTER_READY")}else f>k-1?(f=k-1,q=!0):0>f&&(f=0),q?b(y).trigger("VBPlaylistManager.PLAYLIST_END"):b(y).trigger("VBPlaylistManager.COUNTER_READY")};this.getCounter=function(){return p?P?f:D[f]:f};this.advanceHandler=function(d){P=
!1;fa?(fa=!1,sa+d>k-1?(f=k-1,b(y).trigger("VBPlaylistManager.COUNTER_READY")):0>sa+d?(f=0,b(y).trigger("VBPlaylistManager.COUNTER_READY")):setCounter(sa+d,!1)):y.setCounter(d)};this.processPlaylistRequest=function(b){P=!1;p&&(P=!0,ea=b,fa||(sa=f,fa=!0));y.setCounter(b,!1)};this.setPlaylistItems=function(b,d){"undefined"===typeof d&&(d=!0);d&&(f=-1);k=b;p&&S()};this.reSetCounter=function(b){"undefined"===typeof b?f=-1:(b=parseInt(b,10),k?(b>k-1?b=k-1:0>b&&(b=0),f=b):f=-1)};this.setRandom=function(b){p=
b;3>k&&(p=!1);p&&S();if(p){var d=D.length;for(b=0;b<d;b++)if(D[b]==f){if(0==b)break;b=D.splice(b,1);D.unshift(parseInt(b,10));break}f=0}else fa?(f=ea,fa=!1):f=D[f]};this.setLooping=function(b){T=b};this.getPosition=function(b){return D.indexOf(b)}}})(window,jQuery);
(function(d,b){function P(b,d,k,q){var f={},p=k.width();k=k.height();q=S(d,q);d=q.width;q=q.height;var T=(p-0)/(k-0),y=d/q;y<T?b?(f.width=(k-0)/q*d,f.height=k-0):(f.height=(p-0)/d*q,f.width=p-0):y>T?b?(f.height=(p-0)/d*q,f.width=p-0):(f.width=(k-0)/q*d,f.height=k-0):(f.width=p-0,f.height=k-0);return f}function S(b,d){var k={};"video"==b?d[0].videoWidth&&d[0].videoHeight?(k.width=d[0].videoWidth,k.height=d[0].videoHeight):(k.width=640,k.height=360):"iframe"==b?d.sw&&d.sh?(k.width=d.sw,k.height=d.sh):
(k.width=640,k.height=360):"image"==b&&(k.width=d.width(),k.height=d.height());return k}var y=function(){};y.resizeMedia=function(b,d,k,q){var f,p=k.width();var y=k.height();0==d?f=S(b,q):1==d?f=P(!0,b,k,q):2==d&&(f=P(!1,b,k,q));b=parseInt((p-f.width)/2,10);y=parseInt((y-f.height)/2,10);q.css({width:f.width+"px",height:f.height+"px",left:b+"px",top:y+"px"})};d.VBAspectRatio=y})(window,jQuery);
(function(d){d.fn.vb=function(b){function P(a){if(v){if(!Ma){if("touchstart"==a.type){if(a=a.originalEvent.touches,!(a&&0<a.length))return!1}else a.preventDefault();Ma=!0;ta.on(ua,function(a){a:{if("touchmove"==a.type){if(a.originalEvent.touches&&a.originalEvent.touches.length)var c=a.originalEvent.touches;else if(a.originalEvent.changedTouches&&a.originalEvent.changedTouches.length)c=a.originalEvent.changedTouches;else break a;if(1<c.length)break a;c=c[0]}else c=a;a.preventDefault();S(c)}}).on(va,
function(a){a:if(Ma){Ma=!1;ta.off(ua).off(va);if("touchend"==a.type){if(a.originalEvent.touches&&a.originalEvent.touches.length)var c=a.originalEvent.touches;else if(a.originalEvent.changedTouches&&a.originalEvent.changedTouches.length)c=a.originalEvent.changedTouches;else break a;if(1<c.length)break a;c=c[0]}else c=a;a.preventDefault();S(c)}})}return!1}}function S(a){a=a.pageX-cb.offset().left;0>a?a=0:a>wa&&(a=wa);var c=Math.max(0,Math.min(1,a/wa));if("audio"==e)try{m.currentTime=c*m.duration}catch(bb){console.log(bb)}else if("video"==
e)try{h.currentTime=c*h.duration}catch(bb){console.log(bb)}else"youtube"==e?l.seekTo(c*l.getDuration()):"vimeo"==e&&(0!=xa?n.setCurrentTime(c*xa).then(function(a){})["catch"](function(a){}):n.getDuration().then(function(a){n.setCurrentTime(c*a).then(function(a){})["catch"](function(a){})}))}function y(a){if(v){if(!Na){if("touchstart"==a.type){if(a=a.originalEvent.touches,!(a&&0<a.length))return!1}else a.preventDefault();Na=!0;ta.on(ua,function(a){a:{if("touchmove"==a.type){if(a.originalEvent.touches&&
a.originalEvent.touches.length)var c=a.originalEvent.touches;else if(a.originalEvent.changedTouches&&a.originalEvent.changedTouches.length)c=a.originalEvent.changedTouches;else break a;if(1<c.length)break a;c=c[0]}else c=a;a.preventDefault();p(c)}}).on(va,function(a){a:if(Na){Na=!1;ta.off(ua).off(va);if("touchend"==a.type){if(a.originalEvent.touches&&a.originalEvent.touches.length)var c=a.originalEvent.touches;else if(a.originalEvent.changedTouches&&a.originalEvent.changedTouches.length)c=a.originalEvent.changedTouches;
else break a;if(1<c.length)break a;c=c[0]}else c=a;a.preventDefault();p(c)}})}return!1}}function T(){if(!v)return!1;0<t?(db=t,t=0):t=db;k()}function p(a){Oa?(t=Math.max(0,Math.min(1,(a.pageY-Pa.offset().top)/eb)),t=1-t):t=Math.max(0,Math.min(1,(a.pageX-Pa.offset().left)/eb));k()}function k(a){"undefined"!==typeof a&&(t=a);"undefined"!==typeof t&&("audio"==e?m&&(m.volume=t):"video"==e?h&&(h.volume=t,h.muted=0==t?!0:!1):"youtube"==e?l&&(l.setVolume(100*t),0==t?l.mute():l.unMute()):"vimeo"==e&&n&&n.setVolume(t));
cc.css(Oa?"height":"width",t*eb+"px");0==t?Qa.find("img").attr("src",X+"data/icons/mute.png"):Qa.find("img").attr("src",X+"data/icons/volume.png")}function q(){M||(M=d('<div class="vb-poster-holder"/>').appendTo(w));fb=!0;d(new Image).addClass("vb-media").appendTo(M.show()).on("load",function(){z=d(this);VBAspectRatio.resizeMedia("image",E,w,z);z.addClass("vb-visible");Cb||A.show()}).on("error",function(a){console.log(a)}).attr({src:g.poster})}function f(){if("video_360"==x||"image_360"==x){if("undefined"===
typeof THREE){var a=document.createElement("script");a.type="text/javascript";a.src="https://cdnjs.cloudflare.com/ajax/libs/three.js/105/three.min.js";a.onload=a.onreadystatechange=function(){if(!this.readyState||"complete"==this.readyState)if("undefined"===typeof THREE.OrbitControls){var a=document.createElement("script");a.type="text/javascript";a.src="https://unpkg.com/three@0.85.0/examples/js/controls/OrbitControls.js";a.onload=a.onreadystatechange=function(){this.readyState&&"complete"!=this.readyState||
f()};a.onerror=function(){alert("Error loading "+this.src)};var c=document.getElementsByTagName("script")[0];c.parentNode.insertBefore(a,c)}else f()};a.onerror=function(){alert("Error loading "+this.src)};var c=document.getElementsByTagName("script")[0];c.parentNode.insertBefore(a,c);return}if("undefined"===typeof THREE.OrbitControls){c=document.createElement("script");c.type="text/javascript";c.src="https://unpkg.com/three@0.85.0/examples/js/controls/OrbitControls.js";c.onload=c.onreadystatechange=
function(){this.readyState&&"complete"!=this.readyState||f()};c.onerror=function(){alert("Error loading "+this.src)};a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(c,a);return}}else if("hls"==x){if(!Db){"undefined"===typeof Hls?(a=document.createElement("script"),a.type="text/javascript",a.src="https://cdn.jsdelivr.net/npm/hls.js@latest",a.onload=a.onreadystatechange=function(){this.readyState&&"complete"!=this.readyState||(Eb(),f())},a.onerror=function(){alert("Error loading "+
this.src)},c=document.getElementsByTagName("script")[0],c.parentNode.insertBefore(a,c)):(Eb(),f());return}}else if("dash"==x&&!Fb){"undefined"===typeof dashjs?(a=document.createElement("script"),a.type="text/javascript",a.src="https://cdn.dashjs.org/latest/dash.all.min.js",a.onload=a.onreadystatechange=function(){this.readyState&&"complete"!=this.readyState||(Gb(),f())},a.onerror=function(){alert("Error loading "+this.src)},c=document.getElementsByTagName("script")[0],c.parentNode.insertBefore(a,
c)):(Gb(),f());return}fb&&(B=g.start||0,fb=!1);if("audio"==e)g.slideshow&&(Ca=-1,Ra=g.slideshow.length,Bb()),Hb||(Da=d(document.createElement("audio")).attr("preload",Ib),m=Da[0],Hb=!0),gb=!1,m.src=G,Da.on("ended",function(){la()}).on("loadedmetadata",function(){}).on("canplay",function(){if(!gb){gb=!0;g.playbackRate&&(m.playbackRate=Number(g.playbackRate));B?m.currentTime=B:g.start&&(m.currentTime=g.start);if(F||null!=B){var a=m.play();void 0!==a&&a.then(function(){})["catch"](function(a){A.show()})}else A.show();
B=null}}).on("play",function(){Sa()}).on("pause",function(){Ta()}).on("ratechange",function(){setPlaybackRateActiveMenuItem(m.playbackRate)}).on("error",function(a){d(u).trigger("mediaError",{instance:u,instanceName:I,counter:N})}),F&&m.load();else if("video"==e){g.videoFrameTime&&(G+="#t="+g.videoFrameTime);hb=!1;Jb?(Q.show(),J=Q.find(".vb-media"),h=J[0]):(Q||(Q=d('<div class="vb-video-holder"/>').prependTo(w)),a=" playsinline",ib&&(a=""),c='<video class="vb-media" preload="'+Ib+'"'+a+">",c+='<source src="'+
G+'" />',c+="</video>",Q.show().html(c),J=Q.find(".vb-media"),h=J[0],F&&k(0));Y&&"video_360"==x&&("file:"==window.location.protocol&&console.log("Playing 360 videos requires online server connection!"),Kb||(ha=new THREE.WebGLRenderer({antialias:!0}),ha.setSize(640,360),ha.domElement.className+="vb-canvas-video vb-media",w.prepend(d(ha.domElement)),ma=w.find(".vb-canvas-video"),ya=new THREE.Texture(h),ya.minFilter=THREE.LinearFilter,ya.magFilter=THREE.LinearFilter,ya.format=THREE.RGBFormat,jb=new THREE.Scene,
c=new THREE.SphereGeometry(500,60,40),c.scale(-1,1,1),a=new THREE.MeshBasicMaterial({map:ya}),c=new THREE.Mesh(c,a),jb.add(c),Ua||(Ua=!0,C=new THREE.PerspectiveCamera(90,640/360,.1,1E4),C.position.x+=.1,Z=new THREE.OrbitControls(C,w[0]),Z.enableZoom=!1),Kb=!0));J.on("ended",function(){la()}).on("loadedmetadata",function(){}).on("canplay",function(){if(!hb){hb=!0;Y&&"video_360"==x||VBAspectRatio.resizeMedia("video",E,w,J);g.playbackRate&&(h.playbackRate=Number(g.playbackRate));g.start&&(h.currentTime=
g.start);B?h.currentTime=B:g.start&&(h.currentTime=g.start);if(F||null!=B){var a=h.play();void 0!==a&&a.then(function(){})["catch"](function(a){A.show()})}else A.show();B=null;(Lb||h.webkitSupportsPresentationMode&&"function"===typeof h.webkitSetPresentationMode)&&dc.show()}}).on("canplaythrough",function(){Y&&"video_360"==x||("hls"==x&&VBAspectRatio.resizeMedia("video",E,w,J),J.addClass("vb-visible"))}).on("waiting",function(){}).on("playing",function(){}).on("play",function(){Sa()}).on("pause",
function(){Ta()}).on("seeking",function(){na=!1}).on("seeked",function(){Y&&"video_360"==x&&(na=!0,aa=requestAnimationFrame(kb))}).on("error",function(a){switch(a.target.error.code){case a.target.error.MEDIA_ERR_ABORTED:console.log("You aborted the video playback.");break;case a.target.error.MEDIA_ERR_NETWORK:console.log("A network error caused the video download to fail part-way.");break;case a.target.error.MEDIA_ERR_DECODE:console.log("The video playback was aborted due to a corruption problem or because the video used features your browser did not support.");
break;case a.target.error.MEDIA_ERR_SRC_NOT_SUPPORTED:console.log("The video could not be loaded, either because the server or network failed or because the format is not supported.");break;default:console.log("An unknown error occurred.")}});if("hls"==x)if(Va)ba.attachMedia(h);else if(h.canPlayType("application/vnd.apple.mpegurl"))h.src=G;else if(g.mp4)h.src=g.mp4,h.load();else try{h.src=G,h.load()}catch(uc){alert("This browser or device does not support HLS extension. Please use mp4 video for playback!")}else"dash"==
x?Mb?Nb?ia.attachSource(G):(ia.initialize(h,G,F),Nb=!0):g.mp4?(h.src=g.mp4,h.load()):alert("This browser or device does not support MPEG-DASH extension. Please use mp4 video for playback!"):(h.src=G,h.load());Jb=!0}else if("image"==e)za||(za=d('<div class="vb-image-holder"/>').prependTo(w).hide()),"image_360"==x?("file:"==window.location.protocol&&console.log("Playing 360 video and images requires online server connection!"),Ob||(Ea=new THREE.Scene,c=new THREE.SphereBufferGeometry(500,60,40),c.scale(-1,
1,1),lb=new THREE.TextureLoader,mb=new THREE.MeshBasicMaterial({map:lb}),Pb=new THREE.Mesh(c,mb),Ea.add(Pb),R=new THREE.WebGLRenderer,R.setPixelRatio(window.devicePixelRatio),R.setSize(640,360),R.domElement.className+="vb-canvas-image vb-media",w.prepend(d(R.domElement)),Fa=w.find(".vb-canvas-image"),Ua||(Ua=!0,C=new THREE.PerspectiveCamera(90,640/360,.1,1E4),C.position.x+=.1,Z=new THREE.OrbitControls(C,w[0]),Z.enableZoom=!1),Ob=!0),lb.load(G,function(a){Fa.show();Fa.addClass("vb-visible");mb.map=
a;a=w.width();var c=w.height();R.setSize(a,c);C.aspect=a/c;C.updateProjectionMatrix();Z.addEventListener("change",nb);R.render(Ea,C);U=O=!0;Ga.show();ob=Ha=!0;g.duration&&(ca&&clearTimeout(ca),ca=setTimeout(function(){clearTimeout(this);la()},1E3*g.duration))},function(a){},function(a){})):d(new Image).addClass("vb-media").prependTo(za.show()).on("load",function(){ja=d(this);VBAspectRatio.resizeMedia("image",E,w,ja);ja.addClass("vb-visible");U=O=!0;g.duration&&(ca&&clearTimeout(ca),ca=setTimeout(function(){clearTimeout(this);
la()},1E3*g.duration))}).on("error",function(a){console.log(a)}).attr({src:G,alt:G});else if("youtube"==e){if(Qb)qb&&(c=0,B?c=B:g.start&&(c=g.start),F?l.loadVideoById({videoId:G,startSeconds:c,endSeconds:g.end,suggestedQuality:g.quality}):l.cueVideoById({videoId:G,startSeconds:c,endSeconds:g.end,suggestedQuality:g.quality}));else{V=d('<div class="vb-youtube-holder"/>').prependTo(w);c=window.location.href.split("/");var p=c[0]+"//"+c[2],q=b.youtubeNoCookie?"//www.youtube-nocookie.com/embed/":"//www.youtube.com/embed/";
a="1";ib&&(a="0");var v="ytplayer"+Math.floor(16777215*Math.random());c="&color="+b.youtubePlayerColor;var r="&autoplay=1";r="&origin="+p;c=("https:"==window.location.protocol?"https:":"http:")+q+G+"?enablejsapi=1&controls=0&rel=0&showinfo=0&playsinline="+a+"&modestbranding=1&wmode=transparent&iv_load_policy=3&cc_load_policy=0"+c;/^http/.test(p)&&(c+=r);B?c+="&start="+B:g.start&&(c+="&start="+g.start);g.end&&(c+="&end="+g.end);K=d("<iframe/>",{id:v,frameborder:0,src:c,width:"100%",height:"100%",webkitAllowFullScreen:!0,
mozallowfullscreen:!0,allowFullScreen:!0,allow:"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"}).addClass("vb-media");pb&&K.addClass("vb-yt-clean");V.show().prepend(K);window.YT||(c=document.createElement("script"),c.src="https://www.youtube.com/iframe_api",a=document.getElementsByTagName("script")[0],a.parentNode.insertBefore(c,a));var t=setInterval(function(){window.YT&&window.YT.Player&&(t&&clearInterval(t),l=new YT.Player(v,{events:{onReady:ea,onStateChange:sa,onError:fa}}))},
100);Qb=!0}V.show();!pb&&2==E&&g.width&&g.height&&(K.sw=g.width,K.sh=g.height,VBAspectRatio.resizeMedia("iframe",E,V,K))}else if("vimeo"==e){if(Rb)Sb&&(da.show(),n.loadVideo(g.path),setTimeout(function(){clearTimeout(this);ra()},500));else{da=d('<div class="vb-vimeo-holder"/>').appendTo(w);a="1";ib&&(a="0");r=F?"1":"0";q="loop"==oa?"1":"0";p="player"+Math.floor(16777215*Math.random());c="?color=00ADEF";q="&loop="+q;a="&playsinline="+a;var y="&muted=0";r="&autoplay="+r;F&&(y="&muted=1",r="&autoplay=1",
F=!0,k(0));c="https://player.vimeo.com/video/"+g.path+c+"&byline=1&portrait=1&title=1&autopause=1"+a+q+"&dnt=1&background=1&speed=1"+y+r;g.quality&&(c+="&quality="+g.quality);L=d("<iframe/>",{id:p,frameborder:0,src:c,width:"100%",height:"100%",webkitAllowFullScreen:!0,mozallowfullscreen:!0,allowFullScreen:!0,allow:"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"}).addClass("vb-media");da.show().append(L);window.Vimeo||(c=document.createElement("script"),c.src="https://player.vimeo.com/api/player.js",
a=document.getElementsByTagName("script")[0],a.parentNode.insertBefore(c,a));t=setInterval(function(){window.Vimeo&&(t&&clearInterval(t),n=new Vimeo.Player(L[0]),n.on("loaded",ra),n.on("play",D),n.on("pause",bc),n.on("ended",$b),n.on("error",ac),n.on("timeupdate",Zb),Sb=!0)},100);Rb=!0}2==E&&g.width&&g.height&&(L.sw=g.width,L.sh=g.height,VBAspectRatio.resizeMedia("iframe",E,da,L))}"audio"==e||"video"==e||"youtube"==e||"vimeo"==e?(rb.show(),Qa.show(),Ia.show()):(rb.hide(),Qa.hide(),Ia.hide())}function ea(a){qb=
!0;F&&k(0);F?l.playVideo():(null!=B&&l.playVideo(),K.addClass("vb-visible"))}function sa(a){V.is(":visible")&&-1!=a.data&&(0==a.data?Ja||(Ja=!0,la()):1==a.data?(sb||(Ja=!1,B=null,g.quality&&l.setPlaybackQuality(g.quality),g.playbackRate&&1!=g.playbackRate&&l.setPlaybackRate(Number(g.playbackRate)),fc&&(Aa||(Aa=d('<div class="vb-iframe-blocker"></div>').appendTo(V))),sb=!0),Aa&&!g.is360&&Aa.css("display","block"),Sa()):2==a.data?(Aa&&Aa.css("display","none"),Ta()):3==a.data?K.addClass("vb-visible"):
5==a.data&&(F||K.addClass("vb-visible")))}function fa(a){switch(a.data){case 2:console.log("Error code = "+a.data+": The request contains an invalid parameter value. For example, this error occurs if you specify a video ID that does not have 11 characters, or if the video ID contains invalid characters, such as exclamation points or asterisks.");break;case 100:console.log("Error code = "+a.data+": Video not found, removed, or marked as private");break;case 101:console.log("Error code = "+a.data+": Embedding disabled for this video");
break;case 150:console.log("Error code = "+a.data+": Video not found, removed, or marked as private [same as error 100]")}}function D(){if(!tb){L.addClass("vb-visible");if(g.start||B){var a=B?B:g.start;B=null;n.setCurrentTime(a).then(function(a){})["catch"](function(a){})}n.setPlaybackRate(g.playbackRate||1).then(function(a){})["catch"](function(a){});tb=!0}Sa()}function bc(){e&&"vimeo"!=e||Ta()}function ra(){gc&&(Wa||(Wa=d('<div class="vb-iframe-blocker"></div>').css("display","block").appendTo(da)),
g.is360?Wa.css("display","none"):Wa.css("display","block"));F||null!=B?n.play().then(function(){D()})["catch"](function(a){A.show()}):A.show();L.addClass("vb-visible")}function Zb(a){xa=a.duration;Xa=a.seconds;ub=a.percent}function $b(){la()}function ac(a){console.log("Vimeo Player Error!",a)}function Bb(){pa||(pa=d('<div class="vb-slideshow-holder"/>').appendTo(w));if(1<Ra){Ca++;Ca>Ra-1&&(Ca=0);Tb=g.duration||5E3;var a=g.slideshow[Ca]}else a=g.slideshow[0];d(new Image).addClass("vb-media").appendTo(pa.show()).on("load",
function(){W=d(this);VBAspectRatio.resizeMedia("image",E,pa,W);W.addClass("vb-visible");1<Ra&&(Ya=setTimeout(hc,Tb))}).on("error",function(a){console.log(a)}).attr("src",a)}function hc(){clearTimeout(Ya);W&&(W.remove(),W=null);Bb()}function Eb(){ba=new Hls;Va=Hls.isSupported();Db=!0;Va&&(ba.on(Hls.Events.MEDIA_ATTACHED,function(){ba.loadSource(g.path)}),ba.on(Hls.Events.ERROR,function(a,c){if(c.fatal)switch(c.type){case Hls.ErrorTypes.NETWORK_ERROR:console.log("fatal network error encountered, try to recover");
ba.startLoad();break;case Hls.ErrorTypes.MEDIA_ERROR:console.log("fatal media error encountered, try to recover");ba.recoverMediaError();break;default:ba.destroy()}}))}function Gb(){ia=dashjs.MediaPlayer().create();Fb=!0;ia.setFastSwitchEnabled=!0;ia.on(dashjs.MediaPlayer.events.STREAM_INITIALIZED,function(a){});ia.on(dashjs.MediaPlayer.events.ERROR,function(a){console.log("dashjs.MediaPlayer.events.ERROR "+a.error+" : "+a.event.message)});ia.on(dashjs.MediaPlayer.events.PLAYBACK_ERROR,function(a){console.log("dashjs.MediaPlayer.events.PLAYBACK_ERROR")})}
function la(){d(u).trigger("mediaEnd",{instance:u,instanceName:I,counter:N});if("undefined"!==typeof b.endLink&&!VBUtils.isEmpty(b.endLink))if("_blank"==b.endTarget)window.open(b.endLink);else{vb();window.location=b.endLink;return}var a=g.start||0;"loop"==oa?"audio"==e?m&&(m.currentTime=a,m.play()):"video"==e?h&&(h.currentTime=a,h.play()):"youtube"==e?l&&(Ja=!1,l.seekTo(a),l.playVideo()):"vimeo"==e&&n&&n.setCurrentTime(a):"rewind"==oa?"audio"==e?m&&(m.currentTime=a,m.pause()):"video"==e?h&&(h.currentTime=
a,h.pause()):"youtube"==e?l&&(l.seekTo(a),l.pauseVideo()):"vimeo"==e&&n&&(n.pause(),n.setCurrentTime(a)):"next"==oa?wb():"poster"==oa&&("audio"==e?m&&(m.currentTime=a,m.pause()):"video"==e?(h&&(h.currentTime=a,h.pause()),O=!1,Y&&"video_360"==x?ma&&ma.hide():Q.hide(),q()):"youtube"==e?(l&&(l.seekTo(a),l.pauseVideo()),O=!1,V.hide(),q()):"vimeo"==e&&(n&&(n.pause(),n.setCurrentTime(a)),O=!1,da.hide(),q()))}function vb(){na=!1;aa&&cancelAnimationFrame(aa);qa&&clearInterval(qa);M&&M.hide();z&&(z.remove(),
z=null);w.find(".vb-media").removeClass("vb-visible");Ga.hide();Ha=!1;Z&&(Z.removeEventListener("change",nb),Z.reset());if("audio"==e)m&&(m.pause(),m.src=""),Da&&Da.off("ended canplay canplaythrough loadedmetadata pause play error"),Ya&&clearTimeout(Ya),pa&&pa.hide().empty(),W&&(W=null);else if("video"==e){Va&&"hls"==x&&ba.detachMedia();Mb&&"dash"==x&&ia.attachSource(null);Y&&"video_360"==x&&ma&&ma.hide();if(h){h.pause();try{h.currentTime=0}catch(a){}h.src="";h=null}J&&J.off("loadedmetadata waitingended play pause seeking seeked canplay canplaythrough error");
Q&&Q.hide()}else"youtube"==e?(l&&(Ja=!0,qb&&l.stopVideo(),K&&(K,K.sw=null,K.sh=null)),sb=!1,V&&V.hide()):"vimeo"==e?(ub=Xa=xa=0,n&&(n.unload().then(function(){})["catch"](function(a){console.log(a)}),L&&(L,L.sw=null,L.sh=null)),tb=!1,da&&da.hide()):"image"==e&&(ca&&(clearTimeout(ca),ca=null),"image_360"==x?(Fa&&Fa.hide(),ob=!1):(za&&za.hide(),ja&&(ja.remove(),ja=null)));x=e=null;U=!1;g=null;O=!1;Ub.width(0);Vb.width(0);A.hide();Ia.find("img").attr("src",X+"data/icons/play.png")}function kb(){na&&
(J.readyState===J.HAVE_ENOUGH_DATA&&(ya.needsUpdate=!0),ha.render(jb,C),aa=requestAnimationFrame(kb))}function ic(){var a;if("audio"==e){var c=m.currentTime;var b=m.duration;if("undefined"!==typeof m.buffered&&0!=m.buffered.length){try{var d=m.buffered.end(m.buffered.length-1)}catch(ec){}isNaN(d)||(a=d/b)}}else if("video"==e){if(c=h.currentTime,b=h.duration,"undefined"!==typeof h.buffered&&0!=h.buffered.length){try{d=h.buffered.end(h.buffered.length-1)}catch(ec){}isNaN(d)||(a=d/Math.floor(h.duration))}}else"youtube"==
e?(c=l.getCurrentTime(),b=l.getDuration(),a=l.getVideoLoadedFraction()):"vimeo"==e&&(c=Xa,b=xa,a=ub);VBUtils.isNumber(c)&&VBUtils.isNumber(b)&&(d=parseInt(c,10),d!=Wb&&g.end&&c>=g.end?("loop"!=oa&&"rewind"!=oa&&(qa&&clearInterval(qa),na=!1,aa&&cancelAnimationFrame(aa)),la()):(a&&1!=a&&Ub.width(a*wa),Vb.width(c/b*wa),Wb=d))}function Sa(){A.hide();Ia.find("img").attr("src",X+"data/icons/pause.png");if(!O){O=!0;jc&&(F=!0);k();if(Y&&"video_360"==x){Q.hide();ma.show();Ga.show();Ha=!0;Z.addEventListener("change",
nb);var a=w.width(),c=w.height();ha.setSize(a,c);C.aspect=a/c;C.updateProjectionMatrix();ma.addClass("vb-visible");na=!0;aa&&cancelAnimationFrame(aa);aa=requestAnimationFrame(kb)}qa&&clearInterval(qa);qa=setInterval(ic,250);d(u).trigger("mediaStart",{instance:u,instanceName:I,counter:N})}if(kc&&1<vb_mediaArr.length)for(c=vb_mediaArr.length,a=0;a<c;a++)u!=vb_mediaArr[a].inst&&vb_mediaArr[a].inst.pauseMedia();U=!0;d(u).trigger("mediaPlay",{instance:u,instanceName:I,counter:N})}function Ta(){"image"!=
e&&A.show();Ia.find("img").attr("src",X+"data/icons/play.png");U=!1;d(u).trigger("mediaPause",{instance:u,instanceName:I,counter:N})}function wb(){v&&H.advanceHandler(1,!0)}function nb(){"image_360"==x&&R.render(Ea,C);Ha&&(Ha=!1,setTimeout(function(){clearTimeout(this);Ga.hide()},1E3))}function Xb(){wa=cb.width();if(e)if(z&&VBAspectRatio.resizeMedia("image",E,M,z),"audio"==e)W&&VBAspectRatio.resizeMedia("image",E,pa,W);else if("video"==e)if(Y&&"video_360"==x){if(na){var a=w.width(),c=w.height();ha.setSize(a,
c);C.aspect=a/c;C.updateProjectionMatrix()}}else J&&VBAspectRatio.resizeMedia("video",E,Q,J);else"youtube"==e?pb||2==E&&g.width&&g.height&&VBAspectRatio.resizeMedia("iframe",E,V,K):"vimeo"==e?2==E&&g.width&&g.height&&VBAspectRatio.resizeMedia("iframe",E,da,L):"image"==e&&("image_360"==x?ob&&(a=w.width(),c=w.height(),R.setSize(a,c),C.aspect=a/c,C.updateProjectionMatrix(),R.render(Ea,C)):ja&&VBAspectRatio.resizeMedia("image",E,za,ja))}d(this).hasClass("vb-fixed")?d(this).prependTo(d("body")):b.parentContainer&&
d(this).prependTo(d(b.parentContainer));b=d.extend(!0,{},{sourcePath:"",instanceName:"",preload:"auto",aspectRatio:2,mediaEndAction:"loop",volume:.5,useKeyboardNavigationForPlayback:!1,useMobileNativePlayer:!1,disableRightClick:!1,enableBackgroundPlaybackToggle:!1,youtubeNoCookie:!0,togglePlaybackOnMultipleInstances:!0},b);var X=b.sourcePath,I=b.instanceName,oa=b.mediaEndAction,E=b.aspectRatio,Ib=b.preload,lc=b.useKeyboardNavigationForPlayback,t=b.volume,F=b.autoPlay,jc=F,ib=b.useMobileNativePlayer,
fc=b.blockYoutubeEvents,gc=b.blockVimeoEvents,mc=b.disableRightClick,Cb=b.displayPosterOnMobile,nc=b.enableBackgroundPlaybackToggle,kc=b.togglePlaybackOnMultipleInstances,oc=b.skipPoster,pb=b.forceYoutubeChromeless,r=d(this),w=r.find(".vb-media-holder"),A=r.find(".vb-big-play").on("click",function(){u.togglePlayback()}),Ia=r.find(".vb-playback-toggle").on("click",function(){u.togglePlayback()});r.find(".vb-prev-toggle").on("click",function(){u.previousMedia()});r.find(".vb-next-toggle").on("click",
function(){u.nextMedia()});var Qa=r.find(".vb-volume-wrapper"),Yb=r.find(".vb-volume-toggle"),Ka=r.find(".vb-volume-seekbar"),Pa=r.find(".vb-volume-bg"),cc=r.find(".vb-volume-level"),rb=r.find(".vb-seekbar"),cb=r.find(".vb-progress-bg"),Ub=r.find(".vb-load-level"),Vb=r.find(".vb-progress-level"),Ga=r.find(".vb-vr-info"),xb=VBUtils.isMobile(),pc=VBUtils.volumeCanBeSet(),qc=VBUtils.hasFullscreen(),rc=VBUtils.isChrome();VBUtils.isSafari();VBUtils.isAndroid();var Lb=document.pictureInPictureEnabled,sc=
VBUtils.supportsWebGL(),u=this;d("body");var tc=d(window),ta=d(document),Za=d("html"),O,qa,g,e,G,x,N=0,U,B,La=[],Wb=0,Da,m,Hb,gb,Ca,Ra,pa,W,Ya,Tb,Q,J,h,Jb,hb,za,ca,ja,ba,Va,Db,ia,Mb=window.MediaSource,Fb,Nb,z,fb,M,yb,V,K,l,Qb,qb,sb,Ja,Aa,L,n,da,Rb,tb,Sb,xa=0,Xa=0,ub=0,Wa,aa,Y=!0,Ha,Kb,ma,ha,ya,jb,na,C,Z,Ua,Ob,ob,Fa,lb,mb,Ea,R,Pb;if(nc)w.on("click",function(){u.togglePlayback()});0==r.find(".vb-controls").children().length&&r.find(".vb-controls").remove();"undefined"===typeof window.vb_mediaArr&&(window.vb_mediaArr=
[]);vb_mediaArr.push({inst:u,id:I});sc||(Y=!1,Ga.remove(),rc&&console.log("Turn Hardware Acceleration On Within Chrome Browser to enable 360 video and images!"));lc&&ta.keyup(function(a){a.stopImmediatePropagation();a.preventDefault();if(!v)return!1;var c=a.keyCode;d(a.target);33==c?v&&H.advanceHandler(-1,!0):34==c?wb():32==c?u.togglePlayback():77==c&&T()});if(mc)r.on("contextmenu",function(){return!1});var dc=r.find(".vb-pip-toggle").on("click",function(a){if(h)if(Lb)if(document.pictureInPictureElement)try{document.exitPictureInPicture()}catch(c){}else try{h.requestPictureInPicture()}catch(c){}else h.webkitSupportsPresentationMode&&
"function"===typeof h.webkitSetPresentationMode&&h.webkitSetPresentationMode("picture-in-picture"===h.webkitPresentationMode?"inline":"picture-in-picture")}),Ba="normal",zb;ta.on("fullscreenchange mozfullscreenchange MSFullscreenChange webkitfullscreenchange",function(a){zb==I&&("fullscreen"==Ba?(Ba="normal",$a.find("img").attr("src",X+"data/icons/fullscreen_enter.png"),Za.removeClass("vb-fs-overflow"),r.removeClass("vb-fs"),d(u).trigger("fullscreenExit",{instance:u,instanceName:I}),zb=null):(Ba=
"fullscreen",$a.find("img").attr("src",X+"data/icons/fullscreen_exit.png"),Za.addClass("vb-fs-overflow"),r.addClass("vb-fs"),d(u).trigger("fullscreenEnter",{instance:u,instanceName:I})))});var $a=r.find(".vb-fullscreen-toggle").on("click",function(a){zb=I;a=r[0];qc?a.requestFullscreen?document.fullscreenElement?document.exitFullscreen():a.requestFullscreen():a.webkitRequestFullScreen?document.webkitIsFullScreen?document.webkitCancelFullScreen():a.webkitRequestFullScreen():a.msRequestFullscreen?document.msIsFullscreen||
document.msFullscreenElement?document.msExitFullscreen():a.msRequestFullscreen():a.mozRequestFullScreen&&(document.fullscreenElement||document.mozFullScreenElement?document.mozCancelFullScreen():a.mozRequestFullScreen()):"fullscreen"==Ba?(Ba="normal",$a.find("img").attr("src",X+"data/icons/fullscreen_enter.png"),Za.removeClass("vb-fs-overflow"),r.removeClass("vb-fs"),d(u).trigger("fullscreenExit",{instance:u,instanceName:I})):(Ba="fullscreen",$a.find("img").attr("src",X+"data/icons/fullscreen_exit.png"),
Za.addClass("vb-fs-overflow"),r.addClass("vb-fs"),d(u).trigger("fullscreenEnter",{instance:u,instanceName:I}));"onorientationchange"in window&&setTimeout(function(){Xb()},250)}),Ma,wa=cb.width();if("ontouchstart"in window){var ab="touchstart.ap mousedown.ap";var ua="touchmove.ap mousemove.ap";var va="touchend.ap mouseup.ap"}else window.PointerEvent?(ab="pointerdown.ap",ua="pointermove.ap",va="pointerup.ap"):(ab="mousedown.ap",ua="mousemove.ap",va="mouseup.ap");rb.on(ab,function(a){if(v)return P(a),
!1});var db=.5,Na,Oa=Ka.hasClass("vb-volume-vertical")?!0:!1;Oa?Ka.height():Ka.width();var eb=Oa?Pa.height():Pa.width();k();0>t?t=0:1<t&&(t=1);0!=t&&(db=t);pc||(Ka.remove(),Yb.on("click",function(a){T()}));if(!xb)Yb.on("click",function(a){T()});Ka.on(ab,function(a){y(a);return!1});var H=new VBPlaylistManager({randomPlay:b.randomPlay,loopingOn:b.loopingOn});d(H).on("VBPlaylistManager.COUNTER_READY",function(){e&&vb();N=H.getCounter();g=La[N];e=g.type;d(u).trigger("mediaRequest",{instance:u,instanceName:I,
counter:N});"video_360"==e?(e="video",x="video_360"):"image_360"==e&&(e="image",x="image_360");G="video"==e?xb&&g.pathMobile?g.pathMobile:g.path:g.path;"hls"==e?(e="video",x="hls"):"dash"==e&&(e="video",x="dash");yb=!1;oc||("video"==e||"youtube"==e||"vimeo"==e)&&g.poster&&!F&&(yb=!0);yb?q():f()});window.onYouTubeIframeAPIReady=function(){};var Ab;tc.on("onorientationchange"in window?"orientationchange":"resize",function(){if(!v)return!1;Ab&&clearTimeout(Ab);Ab=setTimeout(Xb,150)});this.playMedia=
function(){if(!v||U)return!1;if("audio"==e){if(m){var a=m.play();void 0!==a&&a.then(function(){})["catch"](function(a){A.show();playerLoader.hide()})}}else"video"==e?z?(M.hide().empty(),z=null,A.hide(),f()):h&&(a=h.play(),void 0!==a&&a.then(function(){})["catch"](function(a){A.show()})):"youtube"==e?z?(M.hide().empty(),z=null,A.hide(),f()):l&&l.playVideo():"vimeo"==e&&(z?(M.hide().empty(),z=null,A.hide(),f()):n&&n.playVideo());U=!0};this.pauseMedia=function(){if(!v||!U)return!1;"audio"==e?m&&m.pause():
"video"==e?h&&h.pause():"youtube"==e?l&&l.pauseVideo():"vimeo"==e&&n&&n.pause();U=!1};this.togglePlayback=function(){if(!v)return!1;if(!(xb&&Cb&&g.poster))if("audio"==e)if(z&&!O)A.hide(),f();else{if(m)if(m.paused){var a=m.play();void 0!==a&&a.then(function(){})["catch"](function(a){A.show();playerLoader.hide()})}else m.pause()}else"video"==e?z&&!O?(M.hide().empty(),z=null,A.hide(),f()):h&&(h.paused?(a=h.play(),void 0!==a&&a.then(function(){})["catch"](function(a){A.show();playerLoader.hide()})):h.pause()):
"youtube"==e?z&&!O?(M.hide().empty(),z=null,A.hide(),f()):l&&(a=l.getPlayerState(),1==a?l.pauseVideo():2==a?l.playVideo():(-1==a||5==a||0==a)&&l.playVideo()):"vimeo"==e&&(z&&!O?(M.hide().empty(),z=null,A.hide(),f()):n&&n.getPaused().then(function(a){a?n.play():n.pause()}))};this.nextMedia=function(){if(!v)return!1;wb()};this.previousMedia=function(){if(!v)return!1;v&&H.advanceHandler(-1,!0)};this.setVolume=function(a){if(!v)return!1;0>a?a=0:1<a&&(a=1);k(a)};this.toggleMute=function(){if(!v)return!1;
T()};this.seek=function(a){if(!v)return!1;"audio"==e?m&&(m.currentTime=a):"video"==e?h&&(h.currentTime=a):"youtube"==e?l&&l.seekTo(a):"vimeo"==e&&n&&n.setCurrentTime(a)};this.getCurrentTime=function(){if(!v)return!1;if("audio"==e){if(m)var a=m.currentTime}else if("video"==e)h&&(a=h.currentTime);else if("youtube"==e)l&&(a=l.getCurrentTime());else if("vimeo"==e)return Xa;return a};this.getDuration=function(){if(!v)return!1;if("audio"==e){if(m)var a=m.duration}else if("video"==e)h&&(a=h.duration);else if("youtube"==
e)l&&(a=l.getDuration());else if("vimeo"==e)return xa;return a};this.setPlaybackRate=function(a){if(!v)return!1;"audio"==e?m&&(m.playbackRate=Number(a)):"video"==e?h&&(h.playbackRate=Number(a)):"youtube"==e?l&&l.setPlaybackRate(Number(a)):"vimeo"==e&&n&&n.setPlaybackRate(a).then(function(a){})["catch"](function(a){})};this.setQuality=function(a){if(!v)return!1;"youtube"==e&&l&&(l.pauseVideo(),l.setPlaybackQuality(a),l.playVideo())};this.setRandom=function(a){if(!v)return!1;"undefined"!==typeof H&&
H.setRandom(a)};this.setLooping=function(a){if(!v)return!1;"undefined"!==typeof H&&H.setLooping(a)};this.cleanMedia=function(){if(!v)return!1;vb()};this.loadMedia=function(a){if(!v||"undefined"===typeof H)return!1;"number"===typeof a?(0>a?a=0:a>ka-1&&(a=ka-1),H.processPlaylistRequest(a)):(La.push(a),ka=La.length,H.setPlaylistItems(ka),H.setCounter(ka-1,!1))};this.getMediaPlaying=function(){return v?U:!1};var v=!0;d(u).trigger("setupDone",{instance:u,instanceName:I});La=b.media;var ka=La.length;H.setPlaylistItems(ka);
"undefined"!=typeof b.activeItem&&(N=b.activeItem);N>ka-1&&(N=ka-1);H.setCounter(N,!1);return this}})(jQuery);